// <auto-generated />
using EmployeeApi.Models.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeApi.Migrations
{
    [DbContext(typeof(McvContext))]
    [Migration("20250902083036_RemovedNav")]
    partial class RemovedNav
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeApi.Models.Entity.Department", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("name");

                    b.HasKey("Name")
                        .HasName("PK__departme__72E12F1A4FF70281");

                    b.ToTable("department", (string)null);
                });

            modelBuilder.Entity("EmployeeApi.Models.Entity.Employee", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("department");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Manager")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("manager");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("salary");

                    b.HasKey("Name")
                        .HasName("PK__employee__72E12F1AD4D247B5");

                    b.HasIndex("DepartmentName");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("EmployeeApi.Models.Entity.Employee", b =>
                {
                    b.HasOne("EmployeeApi.Models.Entity.Department", null)
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentName");
                });

            modelBuilder.Entity("EmployeeApi.Models.Entity.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
